name: flutter_template
description: A Flutter Template to get started quickly
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  kiwi: 2.1.1
  dio: 3.0.10
  retrofit: 1.3.4+1
  provider: 4.3.2+2
  json_serializable: 3.5.0
  niddler_dart: 0.10.2
  shared_preferences: 0.5.12+2
  flutter_secure_storage: 3.3.5
  mockito: 4.1.3
  moor: 3.4.0
  moor_ffi: 0.8.0
  connectivity: 2.0.0
  path_provider: 1.6.22
  flutter_svg: 0.19.1
  path: 1.8.0-nullsafety.1
  scroll_when_needed: 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: 3.4.0
  build_runner: 1.10.3
  retrofit_generator: 1.4.0
  kiwi_generator: 2.1.1
  icapps_translations: 3.0.5
  icapps_generator: 0.3.0
  model_generator: 3.3.0
  icapps_license: 0.0.6


flutter:
  uses-material-design: true
  assets:
    - assets/api/
    - assets/fonts/
    - assets/fonts/open_sans/
    - assets/locale/
    - assets/images/
    - assets/images/icons/
    - assets/images/icons/android/
    - assets/images/icons/ios/

icapps_translations:
  api_key: 'lIWZxNlOz3d461rVMeh3dw' #TODO Update this to the correct api key
  default_language: 'nl'
  languages: ['nl','en']

icapps_license:
  licenses:
    moor_ffi: https://raw.githubusercontent.com/simolus3/moor/develop/moor_ffi/LICENSE